/// Flutter icons FlutterIconCom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIconCom
///      fonts:
///       - asset: fonts/FlutterIconCom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlutterIconCom {
  FlutterIconCom._();

  static const _kFontFam = 'FlutterIconCom';
  static const String? _kFontPkg = null;

  static const IconData bubble_speak = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spreadsheet_app = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nut = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
